..

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -14,5 +14,26 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
+    # - name: E2E Test
+    #   run: |
+    #     export RELEASE_NUMBER=123
+    #     curl -X POST https://api.github.com/repos/Fouz/Trivia-Api/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u 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 --data '{"event_type": "e2e", "client_payload": { "repo": "'"$GITHUB_REPOSITORY"'","PR": "'"${{ github.event.number }}"'","number": "'"$RELEASE_NUMBER"'"}}'
+
+    # - name: Test app
+    #   continue-on-error: true
+    #   # continue-on-error: ${{  github.event_name == 'repository_dispatch'  }}
+    #   id: test-app 
+    #   run: |
+    #     # echo "Testing app (randomly fails)"
+    #     # if [[ $(($RANDOM % 2)) == 0 ]]; then exit 0; else exit 1; fi
+    #     echo "this is an error message!"
+    #     exit 1
+
     - name: print result 
-      run: ls
+      run: |
+        ls
+        DATE=$(date '+%Y-%m-%d %H:%M:%S')
+        cp reports/*.html "$DATE.html";
+        AWS_ACCESS_KEY_ID=AKIAUS5HDPOLLL5BTCHB AWS_SECRET_ACCESS_KEY=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 aws sync reports/ s3://locust-reports-mrsool
+        echo "report available on ${https://locust.mrsool.xyz/"$DATE.html}"
+        if [[ ${{steps.test-app.outcome}}  == "success" ]]; then exit 0; else exit 1; fi
